---
title: "Taxing the Titans : An Econometric Study of Billionaire Wealth Drivers"
author: "Tony De Amorim"
format: html
---

# Accesing the sources

The project's repository is available [here](https://github.com/TonyDeAmorim/Taxing-the-Titans-An-Econometric-Study-of-Billionaire-Wealth-Drivers). 

Our core dataset is available for download directly through [this link](https://www.piie.com/publications/working-papers/origins-superrich-billionaire-characteristics-database). 


```{r}
#| label: Library imports
#| message: false
#| warning: false

library(readxl) # To open the billionaires dataset
library(tidyverse) # To clean, modify and analyze our data
library(ggplot2) # For graphical representation
library(stringr) # To clean the data
```


```{r}
#| label: Data cleaning
#| message: false
#| warning: false

Billionaires_dataset <- read_delim("Database_project/Billionaires_dataset.csv",
  delim = ";", escape_double = FALSE, trim_ws = TRUE
)

IMF <- read_csv("Database_project/IMF_GDP_PPP.csv")
Billionaires <-
  Billionaires_dataset |>
  select(!(25:30)) |> # Removing un-needed variables : notes and sources
  mutate(name = str_remove_all(name, "[.,;()]"))
# Removing typo in the names that might prevent good identification of every billionaires

# Pivoting in order to have one row by billionaire
Pivoted <-
  Billionaires |>
  pivot_wider(
    names_from = year,
    values_from = c(rank, networthusbillion, gdpcurrentus),
    id_cols = name
  )

# Joining the pivoted and the original datasets
Billionaires <-
  Billionaires |>
  select(!c(year, rank, networthusbillion, gdpcurrentus)) |>
  distinct(name, .keep_all = TRUE) |>
  full_join(Pivoted, by = "name")

# Creating a list of every country represented in the dataset
Country <-
  Billionaires |>
  distinct(citizenship)
```



```{r}
#| label: IMF GDP dataset
# Converting the names of the countries from the IMF GDP/PPP dataset that are spelled differently the same way as the countries from the billionaires datset

map_IMF <- c(
  "Bahrain, Kingdom of" = "Bahrain",
  "China, People's Republic of" = "China",
  "Egypt, Arab Republic of" = "Egypt",
  "Hong Kong Special Administrative Region, People's Republic of China" = "Hong Kong",
  "Kazakhstan, Republic of" = "Kazakhstan",
  "Liechtenstein, Principality of" = "Liechtenstein",
  "Lithuania, Republic of" = "Lithuania",
  "Macao Special Administrative Region, People's Republic of China" = "Macau",
  "Netherlands, The" = "Netherlands",
  "Poland, Republic of" = "Poland",
  "Russian Federation" = "Russia",
  "Korea, Republic of" = "South Korea",
  "Eswatini, Kingdom of" = "Swaziland",
  "Taiwan Province of China" = "Taiwan",
  "Tanzania, United Republic of" = "Tanzania",
  "Türkiye, Republic of" = "Turkey",
  "Venezuela, República Bolivariana de" = "Venezuela"
)


#
IMF$COUNTRY <- ifelse(
  IMF$COUNTRY %in% names(map_IMF),
  map[IMF$COUNTRY],
  IMF$COUNTRY
)


liste_pays <- c(
  "Algeria", "Angola", "Argentina", "Australia", "Austria", "Bahrain", "Belgium",
  "Bermuda", "Brazil", "Canada", "Chile", "China", "Colombia", "Cyprus",
  "Czech Republic", "Denmark", "Ecuador", "Egypt", "Finland", "France", "Georgia",
  "Germany", "Greece", "Guernsey", "Hong Kong", "India", "Indonesia", "Ireland",
  "Israel", "Italy", "Japan", "Kazakhstan", "Kuwait", "Lebanon", "Liechtenstein",
  "Lithuania", "Macau", "Malaysia", "Mexico", "Monaco", "Morocco", "Nepal",
  "Netherlands", "New Zealand", "Nigeria", "Norway", "Oman", "Peru", "Philippines",
  "Poland", "Portugal", "Romania", "Russia", "Saudi Arabia", "Singapore",
  "South Africa", "South Korea", "Spain", "St. Kitts and Nevis",
  "Swaziland", "Sweden", "Switzerland", "Taiwan", "Tanzania", "Thailand", "Turkey",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
  "Venezuela", "Vietnam"
)


IMF_reduit <-
  IMF |>
  filter(COUNTRY %in% liste_pays) |>
  select(COUNTRY, `1996`, `2000`, `2014`)
```

```{r}
# Drop monaco et guernesay de la liste des millionaires car pas présents dans la liste GDP de IMF
```



```{r}
#| label: FDI dataset
FDI <- read_csv("Database_project/FDI_WB.csv", skip = 3)

F <-
  FDI |>
  distinct(`Country Name`)

map_WB <- c(
  "Czechia" = "Czech Republic",
  "Egypt, Arab Rep." = "Egypt",
  "Hong Kong SAR, China" = "Hong Kong",
  "Macao SAR, China" = "Macau",
  "Russian Federation" = "Russia",
  "Korea, Rep." = "South Korea",
  "Venezuela, RB" = "Venezuela",
  "Viet Nam" = "Vietnam"
)

FDI$`Country Name` <- ifelse(
  FDI$`Country Name` %in% names(map_WB),
  map_WB[FDI$`Country Name`],
  FDI$`Country Name`
)



FDI_reduit <-
  FDI |>
  filter(`Country Name` %in% liste_pays) |>
  select(`Country Name`, `1996`, `2000`, `2014`)

```


```{r}

Tax_revenue <- read_csv("Database_project/Tax_revenue_dataset.csv")

Tax_revenue$`Country Name` <- ifelse(
  Tax_revenue$`Country Name` %in% names(map_WB),
  map_WB[Tax_revenue$`Country Name`],
  Tax_revenue$`Country Name`
)

Tax_revenue_reduit <-
  Tax_revenue |>
  filter(`Country Name` %in% liste_pays) |> 
  select(`Country Name`,`1996 [YR1996]`,`2000 [YR2000]`,`2014 [YR2014]`)

```


```{r}
#| label: Capital formation

Capital_formation <- read_csv("Database_project/Capital_formation.csv")

Capital_formation$`Country Name` <- ifelse(
  Capital_formation$`Country Name` %in% names(map_WB),
  map_WB[Capital_formation$`Country Name`],
  Capital_formation$`Country Name`
)

Capital_formation_reduit <-
  Capital_formation |>
  filter(`Country Name` %in% liste_pays) |> 
  select(`Country Name`,`1996 [YR1996]`,`2000 [YR2000]`,`2014 [YR2014]`)

```

